spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ks-cms?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Japan
    username: root
    password: 123456
    filters: wall,mergeStat


#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://127.0.0.1:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Japan
    username: root
    password: 1234
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz